{% set name = "fuzzy-rough-learn" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oulenz/fuzzy-rough-learn/archive/{{ version }}.tar.gz
  sha256: 2bcb58cbd8ff495a974ea5f34a982215b78e88bf010d075624f44c426de8f6ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.0
    - pip
  run:
    - python >=3.7.0
    - scipy >=1.1.0
    - numpy >=1.17.0
    - scikit-learn >=0.22.0

test:
  imports:
    - frlearn
    - frlearn.tests
    - frlearn.neighbours.tests

about:
  home: http://github.com/oulenz/fuzzy-rough-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package of tools for fuzzy rough machine learning.

  description: |
    fuzzy-rough-learn is a package of scikit-learn extensions for fuzzy rough machine learning.
  doc_url: http://fuzzy-rough-learn.readthedocs.io/
  dev_url: https://github.com/oulenz/fuzzy-rough-learn

extra:
  recipe-maintainers:
    - oulenz
