travis:
  secure:
    BINSTAR_TOKEN: Zuklk1bHvAJA38nYYEVlT3vyQ9yX75XeUyVuXzGSi5Mw7TrgV8IGvBO0flinl8RET9AbGg4LJKrm0LIUoDkXwLf4tFfEt+JNBwLDMqqG8pm19jQ1+6BO2nTB/QXIFD8B6DvJkqi7imX1hmUnaEuREkAzSo8w40FpXlB+TT1zTgZ04U0pjJYIiTz83Vh+TRiknS9KbkJlpbyFmyLCfo9WkWvdTRwSNRtyuPAB6x38YsUD4tWjF/XXw65skrl6LKGfR+3HXYMsDuj+d4UvITqS2q9mx1yJHE47R6Q2CxZrb9MAf/5L5uanTj3foqcZm+et7xsqYVw4yzgyO+7uC9eIRmRowTNXevikftJ1r90tNx/bpEUPs6KwtdGZZS8aL72Q9breVFpSvW0zI7xvgO2HBJ3fCByXaNXnBamX2yjLcLBSoK4Ahq3GbkAKhAKcsCd3zu0LQd3vC/gGO4SAvgwcl+U/KtqbaZAI3tlUSresiuJhZSrnGUsPVizsmdY8rTFHGFiEpHX+ZbNlL0yhFfdO9Tk2raN28uuuHjNmQ2kF3Ray2fXyfGV6ZOZx380AAFFe3yRimKeSI+M4W0VGjjBqOpY/dgTUyf7o5Bi+KS+eGw25WO+Zg/GGv+bIMbIS0OcyUAlou+4qOklJ1mY5ON2rVOzdIsvV8TYaHbtReDzdsMA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
